### ISSUE TITLE
Add implementation of yeartoday operator

### ISSUE THREAD

**Issue by javihern98** [Meaningful-Data/vtlengine#22]
## Notes:

- Each new class must derive from Unary or Binary, and use its existing method. Focus on just generating the py_op function and ensure you set correctly the class attributes.
- Each execution method must add a related test in pytest (one for dataset, one for component, one for scalar, etc)
- If any Semantic Errors or Runtime Errors must be raised, use existing messages or add new ones.

**Comment by albertohernandez1995** [comment]
Year to day operator has been implemented. This operator returns an integer from a duration given with the following mask: "PY\YDDD\D".
This operator works as follows:

Given the following vtl expression: 'DS_r := DS_1[calc Me_2 := yeartoday(Me_1)];', "P1Y359D" duration will be returned as 724 .

If the mask given has a 'M' instead of a 'Y', a Semantic error will be raised.
