### ISSUE TITLE
Add implementation of monthtoday operator

### ISSUE THREAD

**Issue by javihern98** [Meaningful-Data/vtlengine#23]
## Notes:

- Each new class must derive from Unary or Binary, and use its existing method. Focus on just generating the py_op function and ensure you set correctly the class attributes.
- Each execution method must add a related test in pytest (one for dataset, one for component, one for scalar, etc)
- If any Semantic Errors or Runtime Errors must be raised, use existing messages or add new ones.

**Comment by albertohernandez1995** [comment]
Month to day operator has been implemented. This operator returns an integer from a duration given with the following mask: "PM\MDD\D".
This operator works as follows:

Given the following vtl expression: 'DS_r := DS_1[calc Me_2 := monthtoday(Me_1)];', "P24M4D" duration will be returned as 724 days.

If the mask given has a 'Y' instead of a 'M', a Semantic error will be raised.
